version: "3"
services:
  oracle-db-18.4.0-xe:
    image: oracle-db-18.4.0-xe
    container_name: oracle-db-18.4.0-xe
    hostname: oracle-db-18.4.0-xe
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - db-client
  mysql-db-8.0.25:
    build:
      context: ../../
      dockerfile: docker/local/mysql-db/Dockerfile
    image: mysql-db-8.0.25
    container_name: mysql-db-8.0.25
    hostname: mysql-db-8.0.25
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db-client
    volumes:
      - ./mysql-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./mysql-db/conf.d:/etc/mysql/conf.d:ro
  db-client:
    build:
      context: ../../
      dockerfile: docker/local/db-client/Dockerfile
    image: db-client
    container_name: db-client
    hostname: db-client
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "50000:50000"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - db-client
networks:
  db-client:
