version: "3"
services:
  oracle-db-client:
    build:
      context: ../../
      dockerfile: docker/local/oracle-db/Dockerfile
    image: oracle-db-client
    container_name: oracle-db-client
    hostname: oracle-db-client
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - db-client
  mysql-db-client:
    build:
      context: ../../
      dockerfile: docker/local/mysql-db/Dockerfile
    image: mysql-db-client
    container_name: mysql-db-client
    hostname: mysql-db-client
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - db-client
  db-client:
    build:
      context: ../../
      dockerfile: docker/local/db-client/Dockerfile
    image: db-client
    container_name: db-client
    hostname: db-client
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "50000:50000"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - db-client
networks:
  db-client:
