version: "3"
services:
  oracle-db:
    image: oracle-db
    container_name: oracle-db
    hostname: oracle-db
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - db-client
  db-client:
    build:
      context: ./db-client/
    image: db-client
    container_name: db-client
    hostname: db-client
    dns: 8.8.8.8
    tty: true
    stdin_open: true
    ports:
      - "50000:50000"
    environment:
      - TZ=Asia/Tokyo
      - LANG=ja_JP.utf8
    networks:
      - db-client
    volumes:
      - ./db-client/config:/app/config:ro
      - ./db-client/log:/app/log
      - ../../db-client:/app/db-client:ro
networks:
  db-client:

